# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-07 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WZXX_BT', models.CharField(default='', max_length=255, verbose_name='\u6807\u9898')),
                ('WZXX_FBSJ', models.CharField(default='', max_length=10, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('WZXX_FBNER', models.TextField(verbose_name='\u6b63\u6587')),
                ('WZXX_Lang', models.CharField(default='', max_length=20, verbose_name='\u8bed\u79cd')),
                ('WZXX_LY', models.CharField(default='', max_length=255, verbose_name='\u65b0\u95fb\u6765\u6e90')),
                ('WZXX_URL', models.URLField(default='', max_length=255, verbose_name='\u6765\u6e90\u7f51\u5740')),
                ('WZXX_BK', models.CharField(choices=[('\u77ff\u4e1a\u52a8\u6001', '\u77ff\u4e1a\u52a8\u6001'), ('\u56fe\u7247\u8d44\u8baf', '\u56fe\u7247\u8d44\u8baf'), ('\u5408\u4f5c\u4fe1\u606f', '\u5408\u4f5c\u4fe1\u606f'), ('\u6848\u4f8b\u5206\u6790', '\u6848\u4f8b\u5206\u6790'), ('\u98ce\u571f\u4eba\u60c5', '\u98ce\u571f\u4eba\u60c5'), ('\u5883\u5916\u9879\u76ee', '\u5883\u5916\u9879\u76ee')], default='\u77ff\u4e1a\u52a8\u6001', max_length=50, verbose_name='\u65b0\u95fb\u7248\u5757')),
                ('WZXX_CT', models.DateTimeField(auto_now_add=True, verbose_name='\u722c\u53d6\u65f6\u95f4')),
                ('WZXX_FBZT', models.BooleanField(default=False, verbose_name='\u53d1\u5e03\u72b6\u6001')),
            ],
        ),
    ]
